version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example_pw
#docker exec -it pgsql-dev bash
#psql -h localhost -U postgres
#\l

#or use docker desktop to run sql queries. after this psql -h localhost -U postgres
